name: CI/CD

on:
  push:
    branches:
      - main  # or master if your branch is master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./       # deploy root
          publish_branch: gh-pages
          force_orphan: true
